name: Deploy devwocky
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/devwock.github.io
          fetch-depth: 0
          token: ${{secrets.PAT}}
          submodules: true
      - run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreplay.github.com
          git submodule foreach git pull origin main
          git add foam
          git commit -m "update: foam"
          git push
